### ISSUE TITLE
Change git path in Windows terminal for git icon to use the one provided by git for Windows

### ISSUE THREAD

**Issue by Iliescu-Dorin** [jimbrig/jimsdots#18]
%USERPROFILE%\\OneDrive\\Pictures\\Terminal\\Terminal-Icons\\
to
%SystemDrive%\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico

**Comment by jimbrig** [comment]
If I still used these dotfiles I would. Feel free to change it in a PR though (I would probably set it to use a URL or dynamically via `(where.exe git)[0]` with PowerShell to accommodate non-machine-wide/Program Files Git installations by scoop, etc.

I still reference them a lot but maintaining my dotfiles I've deemed seemingly impossible by now due scale.

thanks for the suggestion though!
